services:
  - type: static
    name: tic-tac-toe-react # Change to "starpath" if using StarPath
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
